<?php /* @var $this Rootd_Link_Block_Gateway */ ?>
<div class="link-gateway">
    <div class="page-title">
        <h1><?php echo $this->getTranslation('protected_title'); ?></h1>
    </div>
    <form id="gateway_form" action="<?php echo $this->getFormAction(); ?>" method="post" enctype="multipart/form-data">
        <p class="notice-text"><?php echo $this->getTranslation('protected_text'); ?></p>
        <div class="fieldset">
            <ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label class="required" for="link_password"><em>*</em><?php echo $this->__('Password'); ?></label>
                        <div class="input-box">
                            <input type="password" id="link_password" name="link_password" class="input-text required-entry" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <div class="controls">
                <button type="submit" class="button" title="<?php echo $this->getTranslation('view_text'); ?>">
                    <span>
                        <span><?php echo $this->getTranslation('view_text'); ?></span>
                    </span>
                </button>
            </div>
        </div>
    </form>
</div>